version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db_container
    restart: always
    environment:
      - POSTGRES_DB=dev_web
      - POSTGRES_SCHEMA=trab
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local